swiftlint_version: 0.25.1
disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - force_try
  - identifier_name
  - nesting
  - redundant_discardable_let
  - todo
  - trailing_comma
  - trailing_newline
  - trailing_whitespace
  - type_name
  - unused_optional_binding
  - xctfail_message
  - file_header
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - file_header
  - multiline_parameters
included:
  - AlphaWallet
excluded:
  - AlphaWallet/Vendors
  - AlphaWallet/R.generated.swift
function_parameter_count:
  warning: 20
  error: 25
line_length:
  warning: 250
  error: 450
large_tuple:
  warning: 4
function_body_length: 80
file_length:
  warning: 600
  error: 1200
 

superfluous_disable_command: warning
reporter: "xcode"
