# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

gem 'fastlane'
gem 'cocoapods', git: 'https://github.com/CocoaPods/CocoaPods.git', ref: '0d9380c1443bcfc96b5c78b50b73d376031c1a9c'
#guard against rubyzip vulnerability
gem "rubyzip", ">= 1.3.0"
gem "excon", ">= 0.71.0"
gem "json", ">= 2.3.0"
#guard against rubyzip vulnerability
gem "addressable", ">= 2.8.0"
gem "cocoapods-downloader", ">= 1.6.0"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
