name: Swift

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.1'
    - name: Build Package
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Test Wallet
      working-directory: ./Example
      run: fastlane test_wallet
    - name: Test Dapp
      working-directory: ./Example
      run: fastlane test_dapp
      

